version: "3.9"

services:
  jellyfin:
    image: jellyfin/jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /data/jellyfin:/config
      - /media:/media
    restart: unless-stopped

  dashy:
    image: lissy93/dashy
    ports:
      - "8080:80"
    restart: unless-stopped
